AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SpaceEyesAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: space-eyes-swagger.json
    
Outputs:

    SpaceEyesAPI:
      Description: "Root API endpoint URL for Prod stage"
      Value: !Sub "https://${SpaceEyesAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"
      Export:
        Name: SpaceEyesAPIRoot